apiVersion: apps/v1
kind: Deployment
metadata:
  name: oncall-alert-correlation-engine
  labels:
    app: oncall-alert-correlation-engine
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oncall-alert-correlation-engine
  template:
    metadata:
      labels:
        app: oncall-alert-correlation-engine
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8088"
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: api
          image: ghcr.io/nagadeepak1998/oncall-alert-correlation-engine:latest
          ports:
            - containerPort: 8088
          readinessProbe:
            httpGet:
              path: /health
              port: 8088
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8088
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]

